apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    enableUserWorkload: true
    prometheusK8s: 
      volumeClaimTemplate:
       spec:
         storageClassName: gp2
         volumeMode: Filesystem
         resources:
           requests:
             storage: 50 Gi    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
   prometheus: 
      retention: 2h 
      resources:
        requests:
          cpu: 200m 
          memory: 1Gi
